//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WealthShareV_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin_Tbl
    {
        public int Id_ad { get; set; }
        public string AdminUserName { get; set; }
        [Required(ErrorMessage ="*Email is required")]
        public string AdminEmail { get; set; }
        [Required(ErrorMessage = "*Password is required")]
        public string AdminPassword { get; set; }
    }
}
