//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WealthShareV_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation_Tbl
    {
        public int Id_donation { get; set; }
        public int Iduser { get; set; }
        public int Idissue { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Progress { get; set; }
    
        public virtual Issue_Tbl Issue_Tbl { get; set; }
    }
}
