//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WealthShareV_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Issue_Tbl()
        {
            this.Donation_Tbl = new HashSet<Donation_Tbl>();
        }
    
        public int Id_issue { get; set; }
        public int UserId { get; set; }
        public string Category { get; set; }
        public string Title { get; set; }
        public string Issue_Description { get; set; }
        public decimal Goal { get; set; }
        public Nullable<decimal> CurrentAmount { get; set; }
        public string IssueStatus { get; set; }
        public string issueImgPath { get; set; }
        public Nullable<int> Cat_Id { get; set; }
    
        public virtual Category_Tbl Category_Tbl { get; set; }
        public virtual Category_Tbl Category_Tbl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation_Tbl> Donation_Tbl { get; set; }
        public virtual User_Tbl User_Tbl { get; set; }
    }
}
