//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WealthShareV_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Tbl()
        {
            this.Issue_Tbl = new HashSet<Issue_Tbl>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        [Required(ErrorMessage ="*Email is required")]
        [EmailAddress]
        public string UserEmail { get; set; }
        [Required(ErrorMessage = "*Password is required")]
        public string UserPassword { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Occupation { get; set; }
        public string AccountStatus { get; set; }
        public string imgPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue_Tbl> Issue_Tbl { get; set; }
    }
}
